### ISSUE TITLE
Add InfoBox Component

### ISSUE THREAD

**Issue by vinitraj10** [Groww/frontatish#86]

**Comment by rushatgabhane** [comment]
Please send me the UI mockups for this component, for styling purpose.

**Comment by vinitraj10** [comment]
@rushatgabhane  sure i ll get back in this thread only!!

**Comment by vinitraj10** [comment]
@amanBhawsar can you help me getting the mockup so that @rushatgabhane  can pickup this one

**Comment by amanBhawsar** [comment]
Hey @rushatgabhane, we have already picked this one up. 

You can pick this **Info Component**: It should be able to handle these use cases as per one's need. You can add even more use cases.

![InfoComponent](https://user-images.githubusercontent.com/40451824/118126977-b0988d80-b416-11eb-8733-ca965af9ffe9.png)

**So, before starting the coding part for any component you should think:** 
```
How you'll be developing it?
What props will you provide?
What states to keep within a component? Are states required?
How can you make it so that other developers can use it by passing different props as per their needs?
Review your own code after developing, Check if optimation is required? How can you prevent re-renders?
```

Before starting development, you can come up with a basic idea of how are you going to implement it. You can share it in this thread itself. We can give feedback and suggestions, then you can begin to develop.

**Comment by rushatgabhane** [comment]
Sure! Thanks for the details @amanBhawsar 

### **Props provided**
- label: string 
  - **required**
- type: 'primary' | 'secondary' _(solid background, or border only)_
  - default: 'primary'
- color: 'info' | 'success' | 'warning' | 'error' _(i.e. colors grey, green, yellow and red respectively)_
  - default: 'info' 
- icon: boolean
  - default: false
- customStyles: ViewStyle
  - default: none

### **Implementation details**
**Colors** : _Helper method will handle this._
Use theme colors based on the props.
The text color for secondary button will depend on dark/light mode.
All other colors don't depend on dark/light mode.

And just use Text component from react-native to display the label.

**I don't think any state is required.**

### **Few thoughts**

What do you think of having different default icons for each color? 
Eg: Red color -> error icon, yellow -> warning icon, green -> checkmark icon, grey -> info icon.

### Additional features

Prop for custom icons?

Ability to dismiss the component by swiping or cross icon?

**Comment by vinitraj10** [comment]
@amanBhawsar  @rushatgabhane  please move the conversation in the new thread which is labeled for `Info` component

**Comment by rushatgabhane** [comment]
@amanBhawsar 
Component development is almost done, but it's hard to differentiate between colors in dark mode.

If you have UI mockups for dark-mode, can you please send them too?
Thanks.

**Comment by rushatgabhane** [comment]
## Progress so far

![Light mode](https://user-images.githubusercontent.com/29673073/118345360-9fe23780-b53c-11eb-9acc-7f50576bec7a.jpg)

**Comment by vinitraj10** [comment]
hey @rushatgabhane nice to see your active contribution to this component,we are working on to get you a figma link for UI mockups so that it will be easier for you to work on designs and won't have any difficulties on `padding` `margin` or colors.
So give us some time we will get back to you ASAP.

One small UI feedback i have that currently components need a bit more padding,but i understand once you get the figma link  you will be fine

**Comment by vinitraj10** [comment]
Also, we saw your proposed API we liked it and we had some feedbacks too over the props API you have proposed, @amanBhawsar will send in this thread so that you can rework on them

**Comment by amanBhawsar** [comment]
Hi @rushatgabhane, You came up with the proper structure and implementation. We went through them and have this feedbacks:
1. In place of variant prop, we can have two different props to control borderColor and backgroundColor separately. Using that we can even create cards with different background colors and borders.
2. For Icon prop, we can have a default icon as present in the design. In order to make it reusable for different cases, we can handle the prop like this.
- If props passed are boolean then we can use them to show/hide the default icon. 
- We can also handle another icon name in place of the default one if the icon prop of string type. 
- Also, if someone needs to show some image, it can be done by passing functional component in which case it will be shown in place of the icon. 
- So, based on the type of Icon prop, we can handle all possible cases.
3. We can use prop name as style in place of customStyle.
4. For label text style, we can have an optional textStyle prop.

About Additional feature you mentioned:
1. Prop for custom icons -  We can handle it in the same icon prop based on the type passed.
2. Ability to dismiss the component by swiping or cross icon - yes, you can extend them in such a way that one can control what they need. We can keep them false by default.

We are working on providing Figma links for both light and dark modes. You can use them for providing finishing your component. 

Please let me know if you face any difficulty or have doubt.

**Comment by vinitraj10** [comment]
@rushatgabhane  we will call this component `InfoBox` so this will look something like this `<InfoBox type="success" message="" />`

**Comment by amanBhawsar** [comment]
Hi @rushatgabhane, We have invited you to the design. You should have received a mail regarding it. 
For dark mode, we will soon be adding mapping for them. For now, you can define the color for light mode and those will be updated for dark mode when we will add the mapping for that color in dark mode.

**Comment by rushatgabhane** [comment]
Sure, sounds good.
Also, thanks for the feedback, it's really helpful!
